class Api::CountriesStateCity
    #attr_accessor :state
    
    def initialize(state)
        cities = {
                "ILOCOS REGION" => "reg1",
                "CAGAYAN VALLEY" => "reg2",
                "CENTRAL LUZON" => "reg3",
                "CALABARZON" => "reg4",
                "MIMAROPA" => "reg17",
                "BICOL REGION" => "reg5",
                "WESTERN VISAYAS" => "reg6",
                "CENTRAL VISAYAS" => "reg7",
                "EASTERN VISAYAS" => "reg8",
                "ZAMBOANGA PENINSULA" => "reg9",
                "NORTHERN MINDANAO" => "reg10",
                "DAVAO REGION" => "reg11",
                "SOCCSKSARGEN" => "reg12",
                "Metro Manila" => "ncr",
                "CORDILLERA ADMINISTRATIVE REGION (CAR)" => "car",
                "AUTONOMOUS REGION IN MUSLIM MINDANAO (ARMM)" => "armm",
                "Caraga" => "caraga"
            }
        @state = cities[state]
    end

    Countries = [
        "Afghanistan",
        "Åland Islands",
        "Albania",
        "Algeria",
        "American Samoa",
        "AndorrA",
        "Angola",
        "Anguilla",
        "Antarctica",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Aruba",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bermuda",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Bouvet Island",
        "Brazil",
        "British Indian Ocean Territory",
        "Brunei Darussalam",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cape Verde",
        "Cayman Islands",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Christmas Island",
        "Cocos (Keeling) Islands",
        "Colombia",
        "Comoros",
        "Congo",
        "Congo, The Democratic Republic of the",
        "Cook Islands",
        "Costa Rica",
        "Cote D'Ivoire",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Falkland Islands (Malvinas)",
        "Faroe Islands",
        "Fiji",
        "Finland",
        "France",
        "French Guiana",
        "French Polynesia",
        "French Southern Territories",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Gibraltar",
        "Greece",
        "Greenland",
        "Grenada",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guernsey",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Heard Island and Mcdonald Islands",
        "Holy See (Vatican City State)",
        "Honduras",
        "Hong Kong",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran, Islamic Republic Of",
        "Iraq",
        "Ireland",
        "Isle of Man",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jersey",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Korea, Democratic People'S Republic of",
        "Korea, Republic of",
        "Kuwait",
        "Kyrgyzstan",
        "Lao People'S Democratic Republic",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libyan Arab Jamahiriya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macao",
        "Macedonia, The Former Yugoslav Republic of",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Martinique",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Mexico",
        "Micronesia, Federated States of",
        "Moldova, Republic of",
        "Monaco",
        "Mongolia",
        "Montserrat",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "Netherlands Antilles",
        "New Caledonia",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Niue",
        "Norfolk Island",
        "Northern Mariana Islands",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestinian Territory, Occupied",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Pitcairn",
        "Poland",
        "Portugal",
        "Puerto Rico",
        "Qatar",
        "Reunion",
        "Romania",
        "Russian Federation",
        "RWANDA",
        "Saint Helena",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Pierre and Miquelon",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia and Montenegro",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Georgia and the South Sandwich Islands",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Svalbard and Jan Mayen",
        "Swaziland",
        "Sweden",
        "Switzerland",
        "Syrian Arab Republic",
        "Taiwan, Province of China",
        "Tajikistan",
        "Tanzania, United Republic of",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tokelau",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Turks and Caicos Islands",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "United States Minor Outlying Islands",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Venezuela",
        "Viet Nam",
        "Virgin Islands, British",
        "Virgin Islands, U.S.",
        "Wallis and Futuna",
        "Western Sahara",
        "Yemen",
        "Zambia",
        "Zimbabwe"
    ]

    PhilippineRegions = [
         "ILOCOS REGION",
         "CAGAYAN VALLEY",
         "CENTRAL LUZON",
         "CALABARZON",
         "MIMAROPA",
         "BICOL REGION",
         "WESTERN VISAYAS",
         "CENTRAL VISAYAS",
         "EASTERN VISAYAS",
         "ZAMBOANGA PENINSULA",
         "NORTHERN MINDANAO",
         "DAVAO REGION",
         "SOCCSKSARGEN",
         "Metro Manila",
         "CORDILLERA ADMINISTRATIVE REGION (CAR)",
         "AUTONOMOUS REGION IN MUSLIM MINDANAO (ARMM)",
         "Caraga" 
    ]

    

    

    def find_city
        reg1 = [           
                "ADAMS",            
                "BACARRA",
                "BADOC",
                "BANGUI",
                "CITY OF BATAC",
                "BURGOS",
                "CARASI",
                "CURRIMAO",
                "DINGRAS",
                "DUMALNEG",
                "BANNA (ESPIRITU)",
                "LAOAG CITY (Capital)",
                "MARCOS",
                "NUEVA ERA",
                "PAGUDPUD",
                "PAOAY",
                "PASUQUIN",
                "PIDDIG",
                "PINILI",
                "SAN NICOLAS",
                "SARRAT",
                "SOLSONA",
                "VINTAR",
                "ALILEM",
                "BANAYOYO",
                "BANTAY",
                "BURGOS",
                "CABUGAO",
                "CITY OF CANDON",
                "CAOAYAN",
                "CERVANTES",
                "GALIMUYOD",
                "GREGORIO DEL PILAR (CONCEPCION)",
                "LIDLIDDA",
                "MAGSINGAL",
                "NAGBUKEL",
                "NARVACAN",
                "QUIRINO (ANGKAKI)",
                "SALCEDO (BAUGEN)",
                "SAN EMILIO",
                "SAN ESTEBAN",
                "SAN ILDEFONSO",
                "SAN JUAN (LAPOG)",
                "SAN VICENTE",
                "SANTA",
                "SANTA CATALINA",
                "SANTA CRUZ",
                "SANTA LUCIA",
                "SANTA MARIA",
                "SANTIAGO",
                "SANTO DOMINGO",
                "SIGAY",
                "SINAIT",
                "SUGPON",
                "SUYO",
                "TAGUDIN",
                "CITY OF VIGAN (Capital)",
                "AGOO",
                "ARINGAY",
                "BACNOTAN",
                "BAGULIN",
                "BALAOAN",
                "BANGAR",
                "BAUANG",
                "BURGOS",
                "CABA",
                "LUNA",
                "NAGUILIAN",
                "PUGO",
                "ROSARIO",
                "CITY OF SAN FERNANDO (Capital)",
                "SAN GABRIEL",
                "SAN JUAN",
                "SANTO TOMAS",
                "SANTOL",
                "SUDIPEN",
                "TUBAO",
                "AGNO",
                "AGUILAR",
                "CITY OF ALAMINOS",
                "ALCALA",
                "ANDA",
                "ASINGAN",
                "BALUNGAO",
                "BANI",
                "BASISTA",
                "BAUTISTA",
                "BAYAMBANG",
                "BINALONAN",
                "BINMALEY",
                "BOLINAO",
                "BUGALLON",
                "BURGOS",
                "CALASIAO",
                "DAGUPAN CITY",
                "DASOL",
                "INFANTA",
                "LABRADOR",
                "LINGAYEN (Capital)",    
                "MABINI",    
                "MALASIQUI",    
                "MANAOAG",    
                "MANGALDAN",    
                "MANGATAREM",    
                "MAPANDAN",    
                "NATIVIDAD",    
                "POZORRUBIO",    
                "ROSALES",    
                "SAN CARLOS CITY",    
                "SAN FABIAN",    
                "SAN JACINTO",    
                "SAN MANUEL",    
                "SAN NICOLAS",    
                "SAN QUINTIN",    
                "SANTA BARBARA",    
                "SANTA MARIA",    
                "SANTO TOMAS",    
                "SISON",    
                "SUAL",    
                "TAYUG",    
                "UMINGAN",    
                "URBIZTONDO",    
                "CITY OF URDANETA",    
                "VILLASIS",    
                "LAOAC"
        ]
    
        reg2 = [    
                "BASCO (Capital)",    
                "ITBAYAT",    
                "IVANA",    
                "MAHATAO",    
                "SABTANG",    
                "UYUGAN",    
                "ABULUG",    
                "ALCALA",    
                "ALLACAPAN",    
                "AMULUNG",    
                "APARRI",    
                "BAGGAO",    
                "BALLESTEROS",    
                "BUGUEY",    
                "CALAYAN",    
                "CAMALANIUGAN",    
                "CLAVERIA",    
                "ENRILE",    
                "GATTARAN",    
                "GONZAGA",    
                "IGUIG",    
                "LAL-LO",    
                "LASAM",    
                "PAMPLONA",    
                "PEÑABLANCA",    
                "PIAT",    
                "RIZAL",    
                "SANCHEZ-MIRA",    
                "SANTA ANA",    
                "SANTA PRAXEDES",    
                "SANTA TERESITA",    
                "SANTO NIÑO (FAIRE)",    
                "SOLANA",    
                "TUAO",    
                "TUGUEGARAO CITY (Capital)",    
                "ALICIA",    
                "ANGADANAN",    
                "AURORA",    
                "BENITO SOLIVEN",    
                "BURGOS",    
                "CABAGAN",    
                "CABATUAN",    
                "CITY OF CAUAYAN",    
                "CORDON",    
                "DINAPIGUE",    
                "DIVILACAN",    
                "ECHAGUE",    
                "GAMU",    
                "ILAGAN CITY (Capital)",    
                "JONES",    
                "LUNA",    
                "MACONACON",    
                "DELFIN ALBANO (MAGSAYSAY)",    
                "MALLIG",    
                "NAGUILIAN",    
                "PALANAN",    
                "QUEZON",    
                "QUIRINO",    
                "RAMON",    
                "REINA MERCEDES",    
                "ROXAS",    
                "SAN AGUSTIN",    
                "SAN GUILLERMO",    
                "SAN ISIDRO",    
                "SAN MANUEL",    
                "SAN MARIANO",    
                "SAN MATEO",    
                "SAN PABLO",    
                "SANTA MARIA",    
                "CITY OF SANTIAGO",    
                "SANTO TOMAS",    
                "TUMAUINI",    
                "AMBAGUIO",    
                "ARITAO",    
                "BAGABAG",    
                "BAMBANG",    
                "BAYOMBONG (Capital)",    
                "DIADI",    
                "DUPAX DEL NORTE",    
                "DUPAX DEL SUR",    
                "KASIBU",    
                "KAYAPA",    
                "QUEZON",    
                "SANTA FE",    
                "SOLANO",    
                "VILLAVERDE",    
                "ALFONSO CASTANEDA",    
                "AGLIPAY",    
                "CABARROGUIS (Capital)",    
                "DIFFUN",    
                "MADDELA",    
                "SAGUDAY",    
                "NAGTIPUNAN"
        ]
    
        reg3 = [    
                "ABUCAY",    
                "BAGAC",    
                "CITY OF BALANGA (Capital)",    
                "DINALUPIHAN",    
                "HERMOSA",    
                "LIMAY",    
                "MARIVELES",    
                "MORONG",    
                "ORANI",    
                "ORION",    
                "PILAR",    
                "SAMAL",    
                "ANGAT",    
                "BALAGTAS (BIGAA)",    
                "BALIUAG",    
                "BOCAUE",    
                "BULACAN",    
                "BUSTOS",    
                "CALUMPIT",    
                "GUIGUINTO",    
                "HAGONOY",    
                "CITY OF MALOLOS (Capital)",    
                "MARILAO",    
                "CITY OF MEYCAUAYAN",    
                "NORZAGARAY",    
                "OBANDO",    
                "PANDI",    
                "PAOMBONG",    
                "PLARIDEL",    
                "PULILAN",    
                "SAN ILDEFONSO",    
                "CITY OF SAN JOSE DEL MONTE",    
                "SAN MIGUEL",    
                "SAN RAFAEL",    
                "SANTA MARIA",    
                "DOÑA REMEDIOS TRINIDAD",    
                "ALIAGA",    
                "BONGABON",    
                "CABANATUAN CITY",    
                "CABIAO",    
                "CARRANGLAN",    
                "CUYAPO",    
                "GABALDON (BITULOK & SABANI)",    
                "CITY OF GAPAN",    
                "GENERAL MAMERTO NATIVIDAD",    
                "GENERAL TINIO (PAPAYA)",    
                "GUIMBA",    
                "JAEN",    
                "LAUR",    
                "LICAB",    
                "LLANERA",    
                "LUPAO",    
                "SCIENCE CITY OF MUÑOZ",    
                "NAMPICUAN",    
                "PALAYAN CITY (Capital)",    
                "PANTABANGAN",    
                "PEÑARANDA",    
                "QUEZON",    
                "RIZAL",    
                "SAN ANTONIO",    
                "SAN ISIDRO",    
                "SAN JOSE CITY",    
                "SAN LEONARDO",    
                "SANTA ROSA",    
                "SANTO DOMINGO",    
                "TALAVERA",    
                "TALUGTUG",    
                "ZARAGOZA",    
                "ANGELES CITY",    
                "APALIT",    
                "ARAYAT",    
                "BACOLOR",    
                "CANDABA",    
                "FLORIDABLANCA",    
                "GUAGUA",    
                "LUBAO",    
                "MABALACAT CITY",    
                "MACABEBE",    
                "MAGALANG",    
                "MASANTOL",    
                "MEXICO",    
                "MINALIN",    
                "PORAC",    
                "CITY OF SAN FERNANDO (Capital)",    
                "SAN LUIS",    
                "SAN SIMON",    
                "SANTA ANA",    
                "SANTA RITA",    
                "SANTO TOMAS",    
                "SASMUAN (Sexmoan)",    
                "ANAO",    
                "BAMBAN",    
                "CAMILING",    
                "CAPAS",    
                "CONCEPCION",    
                "GERONA",    
                "LA PAZ",    
                "MAYANTOC",    
                "MONCADA",    
                "PANIQUI",    
                "PURA",    
                "RAMOS",    
                "SAN CLEMENTE",    
                "SAN MANUEL",    
                "SANTA IGNACIA",    
                "CITY OF TARLAC (Capital)",    
                "VICTORIA",    
                "SAN JOSE",    
                "BOTOLAN",    
                "CABANGAN",    
                "CANDELARIA",    
                "CASTILLEJOS",    
                "IBA (Capital)",    
                "MASINLOC",    
                "OLONGAPO CITY",    
                "PALAUIG",    
                "SAN ANTONIO",    
                "SAN FELIPE",    
                "SAN MARCELINO",    
                "SAN NARCISO",    
                "SANTA CRUZ",    
                "SUBIC",    
                "BALER (Capital)",    
                "CASIGURAN",    
                "DILASAG",    
                "DINALUNGAN",    
                "DINGALAN",    
                "DIPACULAO",    
                "MARIA AURORA",    
                "SAN LUIS"
        ]
    
        reg4 = [
                "AGONCILLO",    
                "ALITAGTAG",    
                "BALAYAN",    
                "BALETE",    
                "BATANGAS CITY (Capital)",    
                "BAUAN",    
                "CALACA",    
                "CALATAGAN",    
                "CUENCA",    
                "IBAAN",    
                "LAUREL",    
                "LEMERY",    
                "LIAN",    
                "LIPA CITY",    
                "LOBO",    
                "MABINI",    
                "MALVAR",    
                "MATAASNAKAHOY",    
                "NASUGBU",    
                "PADRE GARCIA",    
                "ROSARIO",    
                "SAN JOSE",    
                "SAN JUAN",    
                "SAN LUIS",    
                "SAN NICOLAS",    
                "SAN PASCUAL",    
                "SANTA TERESITA",    
                "SANTO TOMAS",    
                "TAAL",    
                "TALISAY",    
                "CITY OF TANAUAN",    
                "TAYSAN",    
                "TINGLOY",    
                "TUY",    
                "ALFONSO",    
                "AMADEO",    
                "BACOOR CITY",    
                "CARMONA",    
                "CAVITE CITY",    
                "CITY OF DASMARIÑAS",    
                "GENERAL EMILIO AGUINALDO",    
                "GENERAL TRIAS",    
                "IMUS CITY",    
                "INDANG",    
                "KAWIT",    
                "MAGALLANES",    
                "MARAGONDON",    
                "MENDEZ (MENDEZ-NUÑEZ)",    
                "NAIC",    
                "NOVELETA",    
                "ROSARIO",    
                "SILANG",    
                "TAGAYTAY CITY",    
                "TANZA",    
                "TERNATE",    
                "TRECE MARTIRES CITY (Capital)",    
                "GEN. MARIANO ALVAREZ",    
                "ALAMINOS",    
                "BAY",    
                "CITY OF BIÑAN",    
                "CABUYAO CITY",    
                "CITY OF CALAMBA",    
                "CALAUAN",    
                "CAVINTI",    
                "FAMY",    
                "KALAYAAN",    
                "LILIW",    
                "LOS BAÑOS",    
                "LUISIANA",    
                "LUMBAN",    
                "MABITAC",    
                "MAGDALENA",    
                "MAJAYJAY",    
                "NAGCARLAN",    
                "PAETE",    
                "PAGSANJAN",    
                "PAKIL",    
                "PANGIL",    
                "PILA",    
                "RIZAL",    
                "SAN PABLO CITY",    
                "CITY OF SAN PEDRO",    
                "SANTA CRUZ (Capital)",    
                "SANTA MARIA",    
                "CITY OF SANTA ROSA",    
                "SINILOAN",    
                "VICTORIA",    
                "AGDANGAN",    
                "ALABAT",    
                "ATIMONAN",    
                "BUENAVISTA",    
                "BURDEOS",    
                "CALAUAG",    
                "CANDELARIA",    
                "CATANAUAN",    
                "DOLORES",    
                "GENERAL LUNA",    
                "GENERAL NAKAR",    
                "GUINAYANGAN",    
                "GUMACA",    
                "INFANTA",    
                "JOMALIG",    
                "LOPEZ",    
                "LUCBAN",    
                "LUCENA CITY (Capital)",    
                "MACALELON",    
                "MAUBAN",    
                "MULANAY",    
                "PADRE BURGOS",    
                "PAGBILAO",    
                "PANUKULAN",    
                "PATNANUNGAN",    
                "PEREZ",    
                "PITOGO",    
                "PLARIDEL",    
                "POLILLO",    
                "QUEZON",    
                "REAL",    
                "SAMPALOC",    
                "SAN ANDRES",    
                "SAN ANTONIO",    
                "SAN FRANCISCO (AURORA)",    
                "SAN NARCISO",    
                "SARIAYA",    
                "TAGKAWAYAN",    
                "CITY OF TAYABAS",    
                "TIAONG",    
                "UNISAN",    
                "ANGONO",    
                "CITY OF ANTIPOLO",    
                "BARAS",    
                "BINANGONAN",    
                "CAINTA",    
                "CARDONA",    
                "JALA-JALA",    
                "RODRIGUEZ (MONTALBAN)",    
                "MORONG",    
                "PILILLA",    
                "SAN MATEO",    
                "TANAY",    
                "TAYTAY",    
                "TERESA"
        ]
    
        @@reg17 = [
                "BOAC (Capital)",    
                "BUENAVISTA",    
                "GASAN",    
                "MOGPOG",    
                "SANTA CRUZ",    
                "TORRIJOS",    
                "ABRA DE ILOG",    
                "CALINTAAN",    
                "LOOC",    
                "LUBANG",    
                "MAGSAYSAY",    
                "MAMBURAO (Capital)",    
                "PALUAN",    
                "RIZAL",    
                "SABLAYAN",    
                "SAN JOSE",    
                "SANTA CRUZ",    
                "BACO",    
                "BANSUD",    
                "BONGABONG",    
                "BULALACAO (SAN PEDRO)",    
                "CITY OF CALAPAN (Capital)",    
                "GLORIA",    
                "MANSALAY",    
                "NAUJAN",    
                "PINAMALAYAN",    
                "POLA",    
                "PUERTO GALERA",    
                "ROXAS",    
                "SAN TEODORO",    
                "SOCORRO",    
                "VICTORIA",    
                "ABORLAN",    
                "AGUTAYA",    
                "ARACELI",    
                "BALABAC",    
                "BATARAZA",    
                "BROOKE'S POINT",    
                "BUSUANGA",    
                "CAGAYANCILLO",    
                "CORON",    
                "CUYO",    
                "DUMARAN",    
                "EL NIDO (BACUIT)",    
                "LINAPACAN",    
                "MAGSAYSAY",    
                "NARRA",    
                "PUERTO PRINCESA CITY (Capital)",    
                "QUEZON",    
                "ROXAS",    
                "SAN VICENTE",    
                "TAYTAY",    
                "KALAYAAN",    
                "CULION",    
                "RIZAL (MARCOS)",    
                "SOFRONIO ESPAÑOLA",    
                "ALCANTARA",    
                "BANTON",    
                "CAJIDIOCAN",    
                "CALATRAVA",    
                "CONCEPCION",    
                "CORCUERA",    
                "LOOC",    
                "MAGDIWANG",    
                "ODIONGAN",    
                "ROMBLON (Capital)",    
                "SAN AGUSTIN",    
                "SAN ANDRES",    
                "SAN FERNANDO",    
                "SAN JOSE",    
                "SANTA FE",    
                "FERROL",    
                "SANTA MARIA (IMELDA)"
        ]
    
        reg5 = [
                "BACACAY",    
                "CAMALIG",    
                "DARAGA (LOCSIN)",    
                "GUINOBATAN",    
                "JOVELLAR",    
                "LEGAZPI CITY (Capital)",    
                "LIBON",    
                "CITY OF LIGAO",    
                "MALILIPOT",    
                "MALINAO",    
                "MANITO",    
                "OAS",    
                "PIO DURAN",    
                "POLANGUI",    
                "RAPU-RAPU",    
                "SANTO DOMINGO (LIBOG)",    
                "CITY OF TABACO",    
                "TIWI",    
                "BASUD",    
                "CAPALONGA",    
                "DAET (Capital)",    
                "SAN LORENZO RUIZ (IMELDA)",    
                "JOSE PANGANIBAN",    
                "LABO",    
                "MERCEDES",    
                "PARACALE",    
                "SAN VICENTE",    
                "SANTA ELENA",    
                "TALISAY",    
                "VINZONS",    
                "BAAO",    
                "BALATAN",    
                "BATO",    
                "BOMBON",    
                "BUHI",    
                "BULA",    
                "CABUSAO",    
                "CALABANGA",    
                "CAMALIGAN",    
                "CANAMAN",    
                "CARAMOAN",    
                "DEL GALLEGO",    
                "GAINZA",    
                "GARCHITORENA",    
                "GOA",    
                "IRIGA CITY",    
                "LAGONOY",    
                "LIBMANAN",    
                "LUPI",    
                "MAGARAO",    
                "MILAOR",    
                "MINALABAC",    
                "NABUA",    
                "NAGA CITY",    
                "OCAMPO",    
                "PAMPLONA",    
                "PASACAO",    
                "PILI (Capital)",    
                "PRESENTACION (PARUBCAN)",    
                "RAGAY",    
                "SAGÑAY",    
                "SAN FERNANDO",    
                "SAN JOSE",    
                "SIPOCOT",    
                "SIRUMA",    
                "TIGAON",    
                "TINAMBAC",    
                "BAGAMANOC",    
                "BARAS",    
                "BATO",    
                "CARAMORAN",    
                "GIGMOTO",    
                "PANDAN",    
                "PANGANIBAN (PAYO)",    
                "SAN ANDRES (CALOLBON)",    
                "SAN MIGUEL",    
                "VIGA",    
                "VIRAC (Capital)",    
                "AROROY",    
                "BALENO",    
                "BALUD",    
                "BATUAN",    
                "CATAINGAN",    
                "CAWAYAN",    
                "CLAVERIA",    
                "DIMASALANG",    
                "ESPERANZA",    
                "MANDAON",    
                "CITY OF MASBATE (Capital)",    
                "MILAGROS",    
                "MOBO",    
                "MONREAL",    
                "PALANAS",    
                "PIO V. CORPUZ (LIMBUHAN)",    
                "PLACER",    
                "SAN FERNANDO",    
                "SAN JACINTO",    
                "SAN PASCUAL",    
                "USON",    
                "BARCELONA",    
                "BULAN",    
                "BULUSAN",    
                "CASIGURAN",    
                "CASTILLA",    
                "DONSOL",    
                "GUBAT",    
                "IROSIN",    
                "JUBAN",    
                "MAGALLANES",    
                "MATNOG",    
                "PILAR",    
                "PRIETO DIAZ",    
                "SANTA MAGDALENA",    
                "CITY OF SORSOGON (Capital)",    
                "ALTAVAS"
        ]
    
        reg6 = [
                "ALTAVAS",    
                "BALETE",    
                "BANGA",    
                "BATAN",    
                "BURUANGA",    
                "IBAJAY",    
                "KALIBO (Capital)",    
                "LEZO",    
                "LIBACAO",    
                "MADALAG",    
                "MAKATO",    
                "MALAY",    
                "MALINAO",    
                "NABAS",    
                "NEW WASHINGTON",    
                "NUMANCIA",    
                "TANGALAN",    
                "ANINI-Y",    
                "BARBAZA",    
                "BELISON",    
                "BUGASONG",    
                "CALUYA",    
                "CULASI",    
                "TOBIAS FORNIER (DAO)",    
                "HAMTIC",    
                "LAUA-AN",    
                "LIBERTAD",    
                "PANDAN",    
                "PATNONGON",    
                "SAN JOSE (Capital)",    
                "SAN REMIGIO",    
                "SEBASTE",    
                "SIBALOM",    
                "TIBIAO",    
                "VALDERRAMA",    
                "CUARTERO",    
                "DAO",    
                "DUMALAG",    
                "DUMARAO",    
                "IVISAN",    
                "JAMINDAN",    
                "MA-AYON",    
                "MAMBUSAO",    
                "PANAY",    
                "PANITAN",    
                "PILAR",    
                "PONTEVEDRA",    
                "PRESIDENT ROXAS",    
                "ROXAS CITY (Capital)",    
                "SAPI-AN",    
                "SIGMA",    
                "TAPAZ",    
                "AJUY",    
                "ALIMODIAN",    
                "ANILAO",    
                "BADIANGAN",    
                "BALASAN",    
                "BANATE",    
                "BAROTAC NUEVO",    
                "BAROTAC VIEJO",    
                "BATAD",    
                "BINGAWAN",    
                "CABATUAN",    
                "CALINOG",    
                "CARLES",    
                "CONCEPCION",    
                "DINGLE",    
                "DUEÑAS",    
                "DUMANGAS",    
                "ESTANCIA",    
                "GUIMBAL",    
                "IGBARAS",    
                "ILOILO CITY (Capital)",    
                "JANIUAY",    
                "LAMBUNAO",    
                "LEGANES",    
                "LEMERY",    
                "LEON",    
                "MAASIN",    
                "MIAGAO",    
                "MINA",    
                "NEW LUCENA",    
                "OTON",    
                "CITY OF PASSI",    
                "PAVIA",    
                "POTOTAN",    
                "SAN DIONISIO",    
                "SAN ENRIQUE",    
                "SAN JOAQUIN",    
                "SAN MIGUEL",    
                "SAN RAFAEL",    
                "SANTA BARBARA",    
                "SARA",    
                "TIGBAUAN",    
                "TUBUNGAN",    
                "ZARRAGA",    
                "BACOLOD CITY (Capital)",    
                "BAGO CITY",    
                "BINALBAGAN",    
                "CADIZ CITY",    
                "CALATRAVA",    
                "CANDONI",    
                "CAUAYAN",    
                "ENRIQUE B. MAGALONA (SARAVIA)",    
                "CITY OF ESCALANTE",    
                "CITY OF HIMAMAYLAN",    
                "HINIGARAN",    
                "HINOBA-AN (ASIA)",    
                "ILOG",    
                "ISABELA",    
                "CITY OF KABANKALAN",    
                "LA CARLOTA CITY",    
                "LA CASTELLANA",    
                "MANAPLA",    
                "MOISES PADILLA (MAGALLON)",    
                "MURCIA",    
                "PONTEVEDRA",    
                "PULUPANDAN",    
                "SAGAY CITY",    
                "SAN CARLOS CITY",    
                "SAN ENRIQUE",    
                "SILAY CITY",    
                "CITY OF SIPALAY",    
                "CITY OF TALISAY",    
                "TOBOSO",    
                "VALLADOLID",    
                "CITY OF VICTORIAS",    
                "SALVADOR BENEDICTO",    
                "BUENAVISTA",    
                "JORDAN (Capital)",    
                "NUEVA VALENCIA",    
                "SAN LORENZO",    
                "SIBUNAG"
        ]

        ncr = [
                "Caloocan City",
                "Las Piñas City",
                "Makati City",
                "Malabon City",
                "Mandaluyong City",
                "Manila City",
                "Marikina City",
                "Muntinlupa City",
                "Navotas City",
                "Parañaque City",
                "Pasay City",
                "Pasig City",
                "Pateros City",
                "Quezon City",
                "San Juan City",
                "Taguig City",
                "Valenzuela City"
            ]
        return eval(@state)
    end
end